spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: attendance-service
          #uri: http://localhost:8081
          uri: lb://attendance-service
          predicates:
            - Path=/attendance/**

        - id: leave-management-service
          #uri: http://localhost:8082
          uri: lb://leave-management-service
          predicates:
            - Path=/leave/**

        - id: leave-balance-service
          #uri: http://localhost:8083
          uri: lb://leave-balance-service
          predicates:
            - Path=/balance/**

        - id: shift-service
          #uri: http://localhost:8084
          uri: lb://shift-service
          predicates:
            - Path=/shifts/**

        - id: reports-analytics-service
          #uri: http://localhost:8085
          uri: lb://reports-analytics-service
          predicates:
            - Path=/report/**

        - id: employee-service
          #uri: http://localhost:8086
          uri: lb://employee-service
          predicates:
            - Path=/employees/**

server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka		