server:
  port: 8084

spring:
  application:
    name: leave-balance-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leavebalancedb
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update


  eureka:
    instance:
      hostname: ${vcap.application.uris[0]:localhost}
      metadataMap:
        instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      leaseRenewalIntervalInSeconds: 5
    client:
      region: default
      registryFetchIntervalSeconds: 5
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true