package com.elams.dtos;

import com.elams.enums.ShiftStatusType;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Data Transfer Object (DTO) representing the status of a shift.
 * This class encapsulates shift status information, including the status ID, shift ID, shift status type,
 * and the ID of the employee requested for a swap.
 * It is used for transferring shift status data between different layers of the application.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ShiftStatusDTO {

    @Schema(name = "id", description = "Autogenerated value, should not be added.", defaultValue = "null", requiredMode = Schema.RequiredMode.NOT_REQUIRED, hidden = true)
    private Long id;

    @NotNull(message = "Shift Id is required")
    @Positive(message = "Shift Id must be a positive number")
    @Schema(name = "shiftId", description = "Should be a valid Shift Id", requiredMode = Schema.RequiredMode.REQUIRED)
    private Long shiftId;

    @NotNull(message = "Shift status is required")
    @Schema(name = "shiftStatus", description = "Status of Shift, can be OPEN, SCHEDULED, COMPLETED, SWAP_REQUEST_REJECTED, SWAP_REQUESTED, SWAP_REQUEST_APPROVED", requiredMode = Schema.RequiredMode.REQUIRED)
    private ShiftStatusType status;

    @Positive(message = "Requested Swap Employee Id must be a positive number")
    @Schema(name = "requestedSwapEmployeeId", description = "Should be a valid Requested Swap Employee Id during Swap Request")
    private Long requestedSwapEmployeeId;
}