package com.elams.dtos;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.Valid;
import jakarta.validation.constraints.FutureOrPresent;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Data Transfer Object (DTO) representing a shift.
 * This class encapsulates shift information, including shift ID, employee ID, shift date, shift time, and shift status.
 * It is used for transferring shift data between different layers of the application.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class ShiftDTO {

    @Schema(name = "shiftId", description = "Autogenerated value, should not be added.", defaultValue = "null", requiredMode = Schema.RequiredMode.NOT_REQUIRED, hidden = true)
    private Long shiftId;

    @NotNull(message = "Employee Id is required")
    @Positive(message = "Employee Id must be a positive number")
    @Schema(name = "employeeId", description = "Should be a valid Employee Id", requiredMode = Schema.RequiredMode.REQUIRED)
    private Long employeeId;

    @NotNull(message = "Shift date is required")
    @FutureOrPresent(message = "Shift date must be in the present or future")
    @Schema(name = "shiftDate", description = "Represents the shift date of Employee, should be valid Date in திறன்-MM-DD format", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalDate shiftDate;

    @NotNull(message = "Shift time is required")
    @Schema(name = "shiftTime", description = "Represents the shift time of Employee, should be valid time in HH:MM:SS format", type = "string", example = "23:00:00", requiredMode = Schema.RequiredMode.REQUIRED)
    private LocalTime shiftTime;

    @Schema(hidden = true)
    @Valid
    private ShiftStatusDTO shiftStatus;
}